# Generated by Django 5.0.7 on 2024-07-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo5',
        ),
    ]
