# Generated by Django 5.0.7 on 2024-07-28 11:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tourguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='num_raters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='total_ratings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tourguide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.tourguide')),
            ],
        ),
    ]
